import { AirFare, Profile, TravelRule } from "./types";

export const defaultProfile: Profile = {
  companyName: "enjoy life株式会社",
  name: "中野 友介",
  department: "代表取締役",
  title: "代表取締役",
};

export const defaultRules: TravelRule[] = [
  {
    id: "rule-ceo-domestic-short",
    startDate: "2026-01-01",
    endDate: "2099-12-31",
    category: "国内近距離出張",
    title: "代表取締役",
    perDiem: 30000,
    lodging: 50000,
    preparation: 0,
    flightClass: "ファーストクラス・プレミアムクラス",
    railClass: "グリーン",
    shipClass: "特等・1等",
    note: "初期登録",
  },
  {
    id: "rule-ceo-domestic-long",
    startDate: "2026-01-01",
    endDate: "2099-12-31",
    category: "国内遠距離出張",
    title: "代表取締役",
    perDiem: 40000,
    lodging: 50000,
    preparation: 0,
    flightClass: "ファーストクラス・プレミアムクラス",
    railClass: "グランクラス・グリーン",
    shipClass: "特等・1等",
    note: "初期登録",
  },
  {
    id: "rule-ceo-overseas",
    startDate: "2026-01-01",
    endDate: "2099-12-31",
    category: "海外出張",
    title: "代表取締役",
    perDiem: 50000,
    lodging: 60000,
    preparation: 20000,
    flightClass: "ファーストクラス",
    railClass: "グリーン",
    shipClass: "特等・1等",
    note: "初期登録",
  },
  {
    id: "rule-director-domestic-short",
    startDate: "2026-01-01",
    endDate: "2099-12-31",
    category: "国内近距離出張",
    title: "取締役",
    perDiem: 20000,
    lodging: 40000,
    preparation: 0,
    flightClass: "ビジネスクラス・プレミアムクラス・クラスJ",
    railClass: "グリーン",
    shipClass: "1等",
    note: "初期登録",
  },
  {
    id: "rule-director-domestic-long",
    startDate: "2026-01-01",
    endDate: "2099-12-31",
    category: "国内遠距離出張",
    title: "取締役",
    perDiem: 30000,
    lodging: 40000,
    preparation: 0,
    flightClass: "ビジネスクラス・プレミアムクラス・クラスJ",
    railClass: "グリーン",
    shipClass: "1等",
    note: "初期登録",
  },
  {
    id: "rule-director-overseas",
    startDate: "2026-01-01",
    endDate: "2099-12-31",
    category: "海外出張",
    title: "取締役",
    perDiem: 40000,
    lodging: 50000,
    preparation: 10000,
    flightClass: "ビジネスクラス",
    railClass: "グリーン",
    shipClass: "1等",
    note: "初期登録",
  },
];

export const defaultAirFares: AirFare[] = [
  {
    id: "jal-itm-hnd-flex",
    airline: "JAL",
    from: "ITM",
    to: "HND",
    fareType: "フレックス",
    amount: 34450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-hnd-itm-flex",
    airline: "JAL",
    from: "HND",
    to: "ITM",
    fareType: "フレックス",
    amount: 34450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-itm-hnd-flex",
    airline: "ANA",
    from: "ITM",
    to: "HND",
    fareType: "フレックス",
    amount: 34450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-hnd-itm-flex",
    airline: "ANA",
    from: "HND",
    to: "ITM",
    fareType: "フレックス",
    amount: 34450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-kix-hnd-flex",
    airline: "JAL",
    from: "KIX",
    to: "HND",
    fareType: "フレックス",
    amount: 33000,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-hnd-kix-flex",
    airline: "JAL",
    from: "HND",
    to: "KIX",
    fareType: "フレックス",
    amount: 33000,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-kix-hnd-flex",
    airline: "ANA",
    from: "KIX",
    to: "HND",
    fareType: "フレックス",
    amount: 33000,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-hnd-kix-flex",
    airline: "ANA",
    from: "HND",
    to: "KIX",
    fareType: "フレックス",
    amount: 33000,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-itm-fuk-flex",
    airline: "JAL",
    from: "ITM",
    to: "FUK",
    fareType: "フレックス",
    amount: 33230,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-fuk-itm-flex",
    airline: "JAL",
    from: "FUK",
    to: "ITM",
    fareType: "フレックス",
    amount: 33230,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-itm-fuk-flex",
    airline: "ANA",
    from: "ITM",
    to: "FUK",
    fareType: "フレックス",
    amount: 33230,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-fuk-itm-flex",
    airline: "ANA",
    from: "FUK",
    to: "ITM",
    fareType: "フレックス",
    amount: 33230,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-itm-cts-flex",
    airline: "JAL",
    from: "ITM",
    to: "CTS",
    fareType: "フレックス",
    amount: 62640,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-cts-itm-flex",
    airline: "JAL",
    from: "CTS",
    to: "ITM",
    fareType: "フレックス",
    amount: 62640,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-itm-cts-flex",
    airline: "ANA",
    from: "ITM",
    to: "CTS",
    fareType: "フレックス",
    amount: 62640,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-cts-itm-flex",
    airline: "ANA",
    from: "CTS",
    to: "ITM",
    fareType: "フレックス",
    amount: 62640,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-itm-sdj-flex",
    airline: "JAL",
    from: "ITM",
    to: "SDJ",
    fareType: "フレックス",
    amount: 46720,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-sdj-itm-flex",
    airline: "JAL",
    from: "SDJ",
    to: "ITM",
    fareType: "フレックス",
    amount: 46720,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-itm-sdj-flex",
    airline: "ANA",
    from: "ITM",
    to: "SDJ",
    fareType: "フレックス",
    amount: 46720,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-sdj-itm-flex",
    airline: "ANA",
    from: "SDJ",
    to: "ITM",
    fareType: "フレックス",
    amount: 46720,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-itm-oka-flex",
    airline: "JAL",
    from: "ITM",
    to: "OKA",
    fareType: "フレックス",
    amount: 56020,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-oka-itm-flex",
    airline: "JAL",
    from: "OKA",
    to: "ITM",
    fareType: "フレックス",
    amount: 56020,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-itm-oka-flex",
    airline: "ANA",
    from: "ITM",
    to: "OKA",
    fareType: "フレックス",
    amount: 56020,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-oka-itm-flex",
    airline: "ANA",
    from: "OKA",
    to: "ITM",
    fareType: "フレックス",
    amount: 56020,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-hnd-oka-flex",
    airline: "JAL",
    from: "HND",
    to: "OKA",
    fareType: "フレックス",
    amount: 61300,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-oka-hnd-flex",
    airline: "JAL",
    from: "OKA",
    to: "HND",
    fareType: "フレックス",
    amount: 61300,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-hnd-oka-flex",
    airline: "ANA",
    from: "HND",
    to: "OKA",
    fareType: "フレックス",
    amount: 61300,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-oka-hnd-flex",
    airline: "ANA",
    from: "OKA",
    to: "HND",
    fareType: "フレックス",
    amount: 61300,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-hnd-fuk-flex",
    airline: "JAL",
    from: "HND",
    to: "FUK",
    fareType: "フレックス",
    amount: 55450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-fuk-hnd-flex",
    airline: "JAL",
    from: "FUK",
    to: "HND",
    fareType: "フレックス",
    amount: 55450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-hnd-fuk-flex",
    airline: "ANA",
    from: "HND",
    to: "FUK",
    fareType: "フレックス",
    amount: 55450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-fuk-hnd-flex",
    airline: "ANA",
    from: "FUK",
    to: "HND",
    fareType: "フレックス",
    amount: 55450,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-hnd-cts-flex",
    airline: "JAL",
    from: "HND",
    to: "CTS",
    fareType: "フレックス",
    amount: 50760,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "jal-cts-hnd-flex",
    airline: "JAL",
    from: "CTS",
    to: "HND",
    fareType: "フレックス",
    amount: 50760,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-hnd-cts-flex",
    airline: "ANA",
    from: "HND",
    to: "CTS",
    fareType: "フレックス",
    amount: 50760,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
  {
    id: "ana-cts-hnd-flex",
    airline: "ANA",
    from: "CTS",
    to: "HND",
    fareType: "フレックス",
    amount: 50760,
    note: "参考額。航空運賃は便・空席・日時で変動するため、実際の表示額に合わせて修正してください。",
  },
];
